export * from './create-suggestion.swagger';
export * from './upload-image.swagger';
export * from './get-suggestions.swagger';
export * from './get-suggestion.swagger';
export * from './get-suggestions-manage.swagger';
export * from './accept-suggestion.swagger';
export * from './reject-suggestion.swagger';
export * from './pending-suggestion.swagger';
export * from './publish-image.swagger';
